project:
  type: website
  output-dir: docs

website:
  title: "Hello, I am Chloe!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Project.qmd
        text: PROJECT


format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

