project:
  type: website
  output-dir: docs

website:
  title: "Hello, I am Chloe!"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Project.qmd


format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

